### ISSUE TITLE
1.0 Release Requirements

### ISSUE THREAD

**Issue by ProjectRevoTPP** [yenatch/pretmap#46]
**Required:**
* [X] #4 Add ability to change a map's width and height
* [X] #5 Add ability to change a map's primary and secondary tilesets
* [X] #14 Add ability to add other types of objects besides people objects
* [x] #15 Give friendly movement type values for map objects.
* [x] #16 Give friendly dropdown values for signpost event "Type" field
* [x] #18 Double-click on warp should open the destination map and auto-select the destination warp
* [x] #27 Add Tooltips to each of the options.
* [x] #30 show neighbouring maps
* [x] #31 movement permissions
* [x] #32 undo/redo buttons

All other issues are optional.

Is there anything else minor we can add before a 1.0 milestone? Anything minor such as #51 .

**Comment by ProjectRevoTPP** [comment]
#37 was already referenced by #14 .

**Comment by ProjectRevoTPP** [comment]
I've sized down the 1.0 requirements to get rid of "nice to have" things.

**Comment by ProjectRevoTPP** [comment]
#21 is related to #4 and #5 since the ability to change these things would also be available when you create a new map. Part of the same goal.

**Comment by ProjectRevoTPP** [comment]
Added some more 1.0 mandatory features at the request of @huderlem .

**Comment by RevoSucks** [comment]
Im going to close this. We met all the feature requirements.
