### ISSUE TITLE
1.1 Release Requirements

### ISSUE THREAD

**Issue by RevoSucks** [yenatch/pretmap#65]
- [ ] #7 Change mouse cursor depending on which of the tools is currently selected
- [ ] #33 Add ability to zoom map view in and out
- [ ] #38 Suggestion for Smart Pathing
- [ ] #51 + type Cursor for dragging the map around
- [ ] #56 A document providing a change log
- [ ] #59 Make Mapping Efficient by Copying Shortcuts From A-Map
- [ ] #60 "Open in Text Editor" button
- [ ] #62 Suggestion
- [ ] #64 Tileset/Blockset Editor
- [ ] #67 A document providing an install guide

**Comment by SBird1337** [comment]
#64 is a duplicate of #62.
